import { Link, useSearchParams } from 'react-router'
import {
	ConsoleField,
	ConsoleInput,
	ConsoleSelect,
	FilterConsole,
} from '#app/components/institute/console.tsx'
import { LevelLegend, PANOFSKY } from '#app/components/institute/descent.tsx'
import {
	Data,
	Display,
	NoRecords,
} from '#app/components/institute/primitives.tsx'
import {
	EditorialCard,
	FeaturePlate,
	RecordRow,
	type WorkSummary,
} from '#app/components/institute/record.tsx'
import { cn, getWorkImgSrc } from '#app/utils/misc.tsx'
import {
	activeFilterCount,
	centuryLabel,
	PAGE_SIZE,
	type ArchiveIndexData,
	type ArchiveWork,
} from './filters.ts'

/**
 * §5: "The index is the homepage." Candid Garden opens not with a hero image
 * but with the archive itself — a one-paragraph institutional statement in
 * Times, then the console, then the records.
 */

function toSummary(work: ArchiveWork): WorkSummary {
	return {
		id: work.id,
		title: work.title,
		artist: work.artist,
		notBefore: work.notBefore,
		notAfter: work.notAfter,
		institution: work.institution,
		objectKey: work.objectKey,
		motifs: work.taggings.map((t) => t.name),
		updatedAt: work.verifiedAt,
	}
}

export function ArchiveIndexView({ data }: { data: ArchiveIndexData }) {
	const { filters, works, total, facets, pageCount } = data
	const [searchParams] = useSearchParams()
	const activeCount = activeFilterCount(filters)
	const isVoidMode = filters.level === 3

	function hrefWith(changes: Record<string, string | number | null>) {
		const next = new URLSearchParams(searchParams)
		for (const [key, value] of Object.entries(changes)) {
			if (value === null || value === '') next.delete(key)
			else next.set(key, String(value))
		}
		// Any change of filter or view returns to the first page; staying on
		// page 9 of a different result set is never what was meant.
		if (!('page' in changes)) next.delete('page')
		const qs = next.toString()
		return qs ? `?${qs}` : '?'
	}

	return (
		<div className={cn(isVoidMode && 'register-void')}>
			{/* ---- The entire hero: a statement, in Times, and nothing else. ---- */}
			<section className="border-rule container border-b py-10 md:py-14">
				<div className="grid gap-8 lg:grid-cols-12">
					<div className="lg:col-span-8">
						<Display as="h1" size="chapter" className="mb-5">
							Index of Art iconography
						</Display>
						<p className="font-body text-prose-lg measure">
							Candid Garden holds{' '}
							<span className="font-data text-data-lg tabular-nums">
								54,497
							</span>{' '}
							artworks from the ARTigo corpus and publishes, for each of them,
							iconographic metadata generated by a language model and structured
							by Panofsky’s three levels of meaning. Readings are provisional.
							Confidence figures are observed agreement rates, not claims to
							truth.
						</p>
					</div>
					<div className="flex flex-col justify-end gap-3 lg:col-span-4">
						<Data className="text-ground-muted">Browse at level</Data>
						<LevelLegend
							current={filters.level}
							hrefFor={(level) => hrefWith({ level })}
						/>
						<p className="font-body text-prose-sm text-ground-muted">
							{PANOFSKY[filters.level].blurb}
						</p>
					</div>
				</div>
			</section>

			{/* ---- The filter console ---- */}
			<section className="container py-8">
				<FilterConsole
					resetTo={filters.level === 1 ? '?' : `?level=${filters.level}`}
					summary={
						<>
							{total.toLocaleString('en-US')} records
							{activeCount ? ` · ${activeCount} filters active` : null}
						</>
					}
				>
					{/* The view mode has to survive a submit, so it rides along hidden. */}
					<input type="hidden" name="level" value={filters.level} />

					<ConsoleField label="Keyword" htmlFor="f-q" hint="title or artist">
						<ConsoleInput
							id="f-q"
							name="q"
							type="search"
							defaultValue={filters.q}
							placeholder="e.g. Judith"
						/>
					</ConsoleField>

					<ConsoleField label="Motif" htmlFor="f-motif" hint="exact tag">
						<ConsoleInput
							id="f-motif"
							name="motif"
							defaultValue={filters.motif}
							placeholder="e.g. garden"
						/>
					</ConsoleField>

					<ConsoleField label="Subject class" htmlFor="f-category">
						<ConsoleSelect
							id="f-category"
							name="category"
							defaultValue={filters.category}
						>
							<option value="">any</option>
							{facets.categories.map((c) => (
								<option key={c} value={c}>
									{c}
								</option>
							))}
						</ConsoleSelect>
					</ConsoleField>

					<ConsoleField label="Period" htmlFor="f-century">
						<ConsoleSelect
							id="f-century"
							name="century"
							defaultValue={filters.century ?? ''}
						>
							<option value="">any</option>
							{facets.centuries.map(({ century, count }) => (
								<option key={century} value={century}>
									{centuryLabel(century)} ({count.toLocaleString('en-US')})
								</option>
							))}
						</ConsoleSelect>
					</ConsoleField>

					<ConsoleField label="Collection" htmlFor="f-institution">
						<ConsoleSelect
							id="f-institution"
							name="institution"
							defaultValue={filters.institution}
						>
							<option value="">any</option>
							{facets.institutions.map((i) => (
								<option key={i} value={i}>
									{i}
								</option>
							))}
						</ConsoleSelect>
					</ConsoleField>

					<ConsoleField
						label="Min. agreement"
						htmlFor="f-agreement"
						hint="annotations per motif"
					>
						<ConsoleSelect
							id="f-agreement"
							name="agreement"
							defaultValue={filters.minAgreement || ''}
						>
							<option value="">any</option>
							<option value="2">2 or more</option>
							<option value="5">5 or more</option>
							<option value="10">10 or more</option>
							<option value="25">25 or more</option>
						</ConsoleSelect>
					</ConsoleField>

					<ConsoleField label="Attribution" htmlFor="f-verification">
						<ConsoleSelect
							id="f-verification"
							name="verification"
							defaultValue={filters.verification}
						>
							<option value="">any</option>
							<option value="VERIFIED">verified</option>
							<option value="PENDING">pending</option>
							<option value="REJECTED">disputed</option>
							<option value="UNREVIEWED">unreviewed</option>
						</ConsoleSelect>
					</ConsoleField>

					<ConsoleField label="Order" htmlFor="f-sort">
						<ConsoleSelect id="f-sort" name="sort" defaultValue={filters.sort}>
							<option value="title">title</option>
							<option value="period">period</option>
							<option value="motifs">motif count</option>
						</ConsoleSelect>
					</ConsoleField>
				</FilterConsole>
			</section>

			{/* ---- The records ---- */}
			<section className="container pb-16">
				{works.length === 0 ? (
					<NoRecords>
						No records match these filters. Try widening the period or clearing
						the motif.
					</NoRecords>
				) : filters.level === 1 ? (
					<LevelOneTable works={works} />
				) : filters.level === 2 ? (
					<LevelTwoGrid works={works} />
				) : (
					<LevelThreeFeatures
						works={works}
						start={(filters.page - 1) * PAGE_SIZE}
						total={total}
					/>
				)}

				<Pagination
					page={filters.page}
					pageCount={pageCount}
					total={total}
					hrefWith={hrefWith}
				/>
			</section>
		</div>
	)
}

/** Level I — inventory. A real table that is allowed to look like a table (§5). */
function LevelOneTable({ works }: { works: Array<ArchiveWork> }) {
	return (
		<div className="overflow-x-auto">
			<table className="min-w-full">
				<caption className="sr-only">
					Works in the archive, shown at Level I: pre-iconographic inventory.
				</caption>
				<thead>
					<tr className="border-rule-strong border-b">
						{['', 'Title', 'Artist', 'Period', 'Collection', 'Motifs'].map(
							(h, i) => (
								<th
									key={h || i}
									scope="col"
									className={cn(
										'font-data text-data-sm text-ground-muted py-2 pr-4 text-left tracking-[0.12em] uppercase',
										h === 'Collection' && 'hidden md:table-cell',
										h === 'Motifs' && 'hidden lg:table-cell',
									)}
								>
									{h || <span className="sr-only">Plate</span>}
								</th>
							),
						)}
					</tr>
				</thead>
				<tbody>
					{works.map((w) => (
						<RecordRow
							key={w.id}
							work={toSummary(w)}
							imgSrc={getWorkImgSrc(w.objectKey)}
						/>
					))}
				</tbody>
			</table>
		</div>
	)
}

/** Level II — the catalogue. Editorial cards at true ratio. */
function LevelTwoGrid({ works }: { works: Array<ArchiveWork> }) {
	return (
		<div className="grid gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
			{works.map((w) => (
				<EditorialCard
					key={w.id}
					work={toSummary(w)}
					imgSrc={getWorkImgSrc(w.objectKey)}
				/>
			))}
		</div>
	)
}

/** Level III — the exhibition. One work at a time, on the deep ground. */
function LevelThreeFeatures({
	works,
	start,
	total,
}: {
	works: Array<ArchiveWork>
	start: number
	total: number
}) {
	return (
		<div className="divide-rule divide-y">
			{works.map((w, i) => (
				<FeaturePlate
					key={w.id}
					work={toSummary(w)}
					imgSrc={getWorkImgSrc(w.objectKey)}
					index={start + i + 1}
					total={total}
				/>
			))}
		</div>
	)
}

function Pagination({
	page,
	pageCount,
	total,
	hrefWith,
}: {
	page: number
	pageCount: number
	total: number
	hrefWith: (changes: Record<string, string | number | null>) => string
}) {
	if (pageCount <= 1) return null
	const from = (page - 1) * PAGE_SIZE + 1
	const to = Math.min(page * PAGE_SIZE, total)
	return (
		<nav
			aria-label="Index pages"
			className="border-rule mt-12 flex flex-wrap items-center justify-between gap-4 border-t pt-4"
		>
			<Data className="text-ground-muted tabular-nums">
				{from.toLocaleString('en-US')}–{to.toLocaleString('en-US')} of{' '}
				{total.toLocaleString('en-US')}
			</Data>
			<div className="flex items-center gap-4">
				{page > 1 ? (
					<Link
						to={hrefWith({ page: page - 1 })}
						rel="prev"
						className="font-data text-data-sm text-link tracking-[0.12em] uppercase underline underline-offset-4"
					>
						← Previous
					</Link>
				) : (
					<span className="font-data text-data-sm text-ground-muted tracking-[0.12em] uppercase opacity-40">
						← Previous
					</span>
				)}
				<Data className="tabular-nums">
					{page} / {pageCount}
				</Data>
				{page < pageCount ? (
					<Link
						to={hrefWith({ page: page + 1 })}
						rel="next"
						className="font-data text-data-sm text-link tracking-[0.12em] uppercase underline underline-offset-4"
					>
						Next →
					</Link>
				) : (
					<span className="font-data text-data-sm text-ground-muted tracking-[0.12em] uppercase opacity-40">
						Next →
					</span>
				)}
			</div>
		</nav>
	)
}
