import { Link, useSearchParams } from 'react-router'
import {
	ConsoleField,
	ConsoleInput,
	ConsoleSelect,
	FilterConsole,
} from '#app/components/institute/console.tsx'
import { LevelLegend, PANOFSKY } from '#app/components/institute/descent.tsx'
import {
	Data,
	Display,
	NoRecords,
} from '#app/components/institute/primitives.tsx'
import {
	EditorialCard,
	FeaturePlate,
	RecordRow,
	type WorkSummary,
} from '#app/components/institute/record.tsx'
import { cn, getWorkImgSrc } from '#app/utils/misc.tsx'
import {
	activeFilterCount,
	centuryLabel,
	isSenseMode,
	PAGE_SIZE,
	SENSE_MAX_LENGTH,
	type ArchiveIndexData,
	type ArchiveWork,
	type SenseReport,
} from './filters.ts'

/**
 * §5: "The index is the homepage." Candid Garden opens not with a hero image
 * but with the archive itself — a one-paragraph institutional statement in
 * Times, then the console, then the records.
 */

function toSummary(work: ArchiveWork): WorkSummary {
	return {
		id: work.id,
		title: work.title,
		artist: work.artist,
		notBefore: work.notBefore,
		notAfter: work.notAfter,
		institution: work.institution,
		objectKey: work.objectKey,
		motifs: work.taggings.map((t) => t.name),
		updatedAt: work.verifiedAt,
	}
}

export function ArchiveIndexView({ data }: { data: ArchiveIndexData }) {
	const { filters, works, total, facets, pageCount, sense } = data
	const [searchParams] = useSearchParams()
	const activeCount = activeFilterCount(filters)
	const isVoidMode = filters.level === 3
	// A failed reading search falls back to the filtered index, so the presence
	// of a phrase and the presence of a ranking are not the same question.
	const ranked = isSenseMode(filters) && !sense?.error

	function hrefWith(changes: Record<string, string | number | null>) {
		const next = new URLSearchParams(searchParams)
		for (const [key, value] of Object.entries(changes)) {
			if (value === null || value === '') next.delete(key)
			else next.set(key, String(value))
		}
		// Any change of filter or view returns to the first page; staying on
		// page 9 of a different result set is never what was meant.
		if (!('page' in changes)) next.delete('page')
		const qs = next.toString()
		return qs ? `?${qs}` : '?'
	}

	return (
		<div className={cn(isVoidMode && 'register-void')}>
			{/* ---- The entire hero: a statement, in Times, and nothing else. ---- */}
			<section className="border-rule container border-b py-10 md:py-14">
				<div className="grid gap-8 lg:grid-cols-12">
					<div className="lg:col-span-8">
						<Display as="h1" size="chapter" className="mb-5">
							Index of Art iconography
						</Display>
						<p className="font-body text-prose-lg measure">
							Candid Garden holds{' '}
							<span className="font-data text-data-lg tabular-nums">
								54,497
							</span>{' '}
							artworks from the ARTigo corpus and publishes, for each of them,
							iconographic metadata generated by a language model and structured
							by Panofsky’s three levels of meaning. Readings are provisional.
							Confidence figures are observed agreement rates, not claims to
							truth.
						</p>
					</div>
					<div className="flex flex-col justify-end gap-3 lg:col-span-4">
						<Data className="text-ground-muted">Browse at level</Data>
						<LevelLegend
							current={filters.level}
							hrefFor={(level) => hrefWith({ level })}
							// The atlas reads the same `sense` param, so a phrase already in
							// the console travels with the reader and arrives lit. The other
							// filters do not: the projection has no notion of a century or a
							// collection, and silently dropping them is honest where
							// pretending to honour them would not be.
							atlasHref={
								filters.sense
									? `/archive/atlas?sense=${encodeURIComponent(filters.sense)}`
									: '/archive/atlas'
							}
						/>
						<p className="font-body text-prose-sm text-ground-muted">
							{PANOFSKY[filters.level].blurb}
						</p>
						{/* The fourth chip leaves the index, so it gets its own line — and
						    the line says what it is not. The descent stops at III; this is
						    where those readings are held, not a step beneath them. */}
						<p className="font-body text-prose-sm text-ground-muted">
							<Link
								to="/archive/atlas"
								className="underline underline-offset-4"
							>
								Latent space
							</Link>{' '}
							is not a fourth level. It is the same Level II and III readings
							seen from outside — as the space the model holds them in.
						</p>
						{/* The one way into the archive that starts from the reader rather
						    than from the record. It belongs beside the atlas because it is
						    built out of the same space: the spread of cards it deals is
						    taken over those readings. */}
						<p className="font-body text-prose-sm text-ground-muted">
							<Link
								to="/archive/drift"
								className="underline underline-offset-4"
							>
								The drift
							</Link>{' '}
							goes the other way: a passage across that same space, pulled and
							pushed by a few dozen works, ending somewhere that is a reading of
							you rather than of them.
						</p>
					</div>
				</div>
			</section>

			{/* ---- The filter console ---- */}
			<section className="container py-8">
				<FilterConsole
					resetTo={filters.level === 1 ? '?' : `?level=${filters.level}`}
					summary={
						ranked ? (
							// The phrase is counted as a filter everywhere else, but here it
							// is the thing producing the result rather than narrowing it —
							// so the count reports only what narrowed the ranking.
							<>
								{total.toLocaleString('en-US')} of{' '}
								{(sense?.candidates ?? 0).toLocaleString('en-US')} nearest
								readings
								{activeCount > 1
									? ` · ${activeCount - 1} ${activeCount === 2 ? 'filter' : 'filters'} narrowing`
									: null}
							</>
						) : (
							<>
								{total.toLocaleString('en-US')} records
								{activeCount
									? ` · ${activeCount} ${activeCount === 1 ? 'filter' : 'filters'} active`
									: null}
							</>
						)
					}
				>
					{/* The view mode has to survive a submit, so it rides along hidden. */}
					<input type="hidden" name="level" value={filters.level} />

					<ConsoleField label="Keyword" htmlFor="f-q" hint="title or artist">
						<ConsoleInput
							id="f-q"
							name="q"
							type="search"
							defaultValue={filters.q}
							placeholder="e.g. Judith"
						/>
					</ConsoleField>

					{/* The one control that searches the readings rather than the
					    catalogue. Sits beside Keyword because the difference between
					    the two is the thing worth teaching, and it is only legible
					    when they are adjacent. */}
					<ConsoleField
						label="Sense"
						htmlFor="f-sense"
						hint="the readings, by meaning"
					>
						<ConsoleInput
							id="f-sense"
							name="sense"
							type="search"
							maxLength={SENSE_MAX_LENGTH}
							defaultValue={filters.sense}
							placeholder="e.g. grief at a deathbed"
						/>
					</ConsoleField>

					<ConsoleField label="Motif" htmlFor="f-motif" hint="exact tag">
						<ConsoleInput
							id="f-motif"
							name="motif"
							defaultValue={filters.motif}
							placeholder="e.g. garden"
						/>
					</ConsoleField>

					<ConsoleField label="Subject class" htmlFor="f-category">
						<ConsoleSelect
							id="f-category"
							name="category"
							defaultValue={filters.category}
						>
							<option value="">any</option>
							{facets.categories.map((c) => (
								<option key={c} value={c}>
									{c}
								</option>
							))}
						</ConsoleSelect>
					</ConsoleField>

					<ConsoleField label="Period" htmlFor="f-century">
						<ConsoleSelect
							id="f-century"
							name="century"
							defaultValue={filters.century ?? ''}
						>
							<option value="">any</option>
							{facets.centuries.map(({ century, count }) => (
								<option key={century} value={century}>
									{centuryLabel(century)} ({count.toLocaleString('en-US')})
								</option>
							))}
						</ConsoleSelect>
					</ConsoleField>

					<ConsoleField label="Collection" htmlFor="f-institution">
						<ConsoleSelect
							id="f-institution"
							name="institution"
							defaultValue={filters.institution}
						>
							<option value="">any</option>
							{facets.institutions.map((i) => (
								<option key={i} value={i}>
									{i}
								</option>
							))}
						</ConsoleSelect>
					</ConsoleField>

					<ConsoleField
						label="Min. agreement"
						htmlFor="f-agreement"
						hint="annotations per motif"
					>
						<ConsoleSelect
							id="f-agreement"
							name="agreement"
							defaultValue={filters.minAgreement || ''}
						>
							<option value="">any</option>
							<option value="2">2 or more</option>
							<option value="5">5 or more</option>
							<option value="10">10 or more</option>
							<option value="25">25 or more</option>
						</ConsoleSelect>
					</ConsoleField>

					<ConsoleField label="Attribution" htmlFor="f-verification">
						<ConsoleSelect
							id="f-verification"
							name="verification"
							defaultValue={filters.verification}
						>
							<option value="">any</option>
							<option value="VERIFIED">verified</option>
							<option value="PENDING">pending</option>
							<option value="REJECTED">disputed</option>
							<option value="UNREVIEWED">unreviewed</option>
						</ConsoleSelect>
					</ConsoleField>

					{/* A ranking has one order. Rather than offer a control that would
					    silently do nothing, the field says what it is doing and keeps
					    the reader's column choice for when the sense is cleared. */}
					{ranked ? (
						<div className="flex flex-col gap-1.5">
							<Data className="text-ground-muted">Order</Data>
							<input type="hidden" name="sort" value={filters.sort} />
							<p className="border-rule-strong font-data text-data text-ground-muted flex h-10 items-center border border-dashed px-3">
								nearest first
							</p>
							<Data className="text-ground-muted normal-case opacity-70">
								fixed while a sense is set
							</Data>
						</div>
					) : (
						<ConsoleField label="Order" htmlFor="f-sort">
							<ConsoleSelect
								id="f-sort"
								name="sort"
								defaultValue={filters.sort}
							>
								<option value="title">title</option>
								<option value="period">period</option>
								<option value="motifs">motif count</option>
							</ConsoleSelect>
						</ConsoleField>
					)}
				</FilterConsole>

				<SenseDisclosure sense={sense} ranked={ranked} />
			</section>

			{/* ---- The records ---- */}
			<section className="container pb-16">
				{works.length === 0 ? (
					ranked ? (
						<NoRecords>
							None of the {(sense?.candidates ?? 0).toLocaleString('en-US')}{' '}
							nearest readings survives these filters. Widen the period or clear
							the motif — the phrase itself found readings.
						</NoRecords>
					) : (
						<NoRecords>
							No records match these filters. Try widening the period or
							clearing the motif.
						</NoRecords>
					)
				) : filters.level === 1 ? (
					<LevelOneTable works={works} showMatch={ranked} />
				) : filters.level === 2 ? (
					<LevelTwoGrid works={works} />
				) : (
					<LevelThreeFeatures
						works={works}
						start={(filters.page - 1) * PAGE_SIZE}
						total={total}
					/>
				)}

				<Pagination
					page={filters.page}
					pageCount={pageCount}
					total={total}
					hrefWith={hrefWith}
				/>
			</section>
		</div>
	)
}

/**
 * §6, "uncertainty as content", applied to a ranking.
 *
 * A ranked search is more capable of misleading than a filter is: it always
 * returns something, it returns it in an order that looks like judgement, and
 * it can only see the readings that have been embedded. So the qualifications
 * travel with the results — what nearness measures, how far the scan reached,
 * and how much of the archive it can reach at all — rather than living in a
 * help page nobody opens.
 */
function SenseDisclosure({
	sense,
	ranked,
}: {
	sense: SenseReport | null
	ranked: boolean
}) {
	if (!sense) return null

	if (sense.error) {
		return (
			<p
				role="note"
				className="border-stamp-fg text-stamp-fg font-data text-data mt-4 border-l-2 py-1 pl-3 tracking-[0.12em] uppercase"
			>
				Reading index unavailable · the phrase “{sense.query}” was not applied ·
				showing the unranked index
			</p>
		)
	}

	if (!ranked) return null

	const { coverage } = sense
	return (
		<div className="border-rule mt-4 border-l pl-3">
			<Data className="text-ground-muted">
				Nearest first · {sense.matched.toLocaleString('en-US')} of{' '}
				{sense.candidates.toLocaleString('en-US')} nearest readings kept
				{sense.capped ? ' · scan capped' : null}
			</Data>
			<p className="font-body text-prose-sm text-ground-muted measure mt-2">
				Nearness is the distance between your phrase and a machine-written
				reading, measured in the embedding space of the model that wrote neither
				of them. It is proximity, not relevance, and it is not evidence that a
				work depicts what you asked for.
				{sense.capped ? (
					<>
						{' '}
						The scan stops at the {sense.candidates.toLocaleString(
							'en-US',
						)}{' '}
						nearest readings before your filters are applied, so this is not
						every work in the archive that could match.
					</>
				) : null}
				{coverage ? (
					<>
						{' '}
						It reaches{' '}
						<span className="font-data tabular-nums">
							{coverage.works.toLocaleString('en-US')}
						</span>{' '}
						works —{' '}
						<span className="font-data tabular-nums">
							{coverage.readings.toLocaleString('en-US')}
						</span>{' '}
						of{' '}
						<span className="font-data tabular-nums">
							{coverage.publishedReadings.toLocaleString('en-US')}
						</span>{' '}
						published readings have been embedded. The rest cannot be found this
						way.
					</>
				) : null}
			</p>
		</div>
	)
}

/** Level I — inventory. A real table that is allowed to look like a table (§5). */
function LevelOneTable({
	works,
	showMatch = false,
}: {
	works: Array<ArchiveWork>
	showMatch?: boolean
}) {
	const columns = [
		'',
		'Title',
		'Artist',
		'Period',
		'Collection',
		'Motifs',
		...(showMatch ? ['Nearness'] : []),
	]
	return (
		<div className="overflow-x-auto">
			<table className="min-w-full">
				<caption className="sr-only">
					Works in the archive, shown at Level I: pre-iconographic inventory.
					{showMatch
						? ' Ordered by the nearness of their readings to the phrase searched for.'
						: null}
				</caption>
				<thead>
					<tr className="border-rule-strong border-b">
						{columns.map((h, i) => (
							<th
								key={h || i}
								scope="col"
								className={cn(
									'font-data text-data-sm text-ground-muted py-2 pr-4 text-left tracking-[0.12em] uppercase',
									h === 'Collection' && 'hidden md:table-cell',
									h === 'Motifs' && 'hidden lg:table-cell',
									h === 'Nearness' && 'pr-0 text-right',
								)}
							>
								{h || <span className="sr-only">Plate</span>}
							</th>
						))}
					</tr>
				</thead>
				<tbody>
					{works.map((w) => (
						<RecordRow
							key={w.id}
							work={toSummary(w)}
							imgSrc={getWorkImgSrc(w.objectKey)}
							match={w.match}
							showMatch={showMatch}
						/>
					))}
				</tbody>
			</table>
		</div>
	)
}

/** Level II — the catalogue. Editorial cards at true ratio. */
function LevelTwoGrid({ works }: { works: Array<ArchiveWork> }) {
	return (
		<div className="grid gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
			{works.map((w) => (
				<EditorialCard
					key={w.id}
					work={toSummary(w)}
					imgSrc={getWorkImgSrc(w.objectKey)}
					match={w.match}
				/>
			))}
		</div>
	)
}

/** Level III — the exhibition. One work at a time, on the deep ground. */
function LevelThreeFeatures({
	works,
	start,
	total,
}: {
	works: Array<ArchiveWork>
	start: number
	total: number
}) {
	return (
		<div className="divide-rule divide-y">
			{works.map((w, i) => (
				<FeaturePlate
					key={w.id}
					work={toSummary(w)}
					imgSrc={getWorkImgSrc(w.objectKey)}
					index={start + i + 1}
					total={total}
					match={w.match}
				/>
			))}
		</div>
	)
}

function Pagination({
	page,
	pageCount,
	total,
	hrefWith,
}: {
	page: number
	pageCount: number
	total: number
	hrefWith: (changes: Record<string, string | number | null>) => string
}) {
	if (pageCount <= 1) return null
	const from = (page - 1) * PAGE_SIZE + 1
	const to = Math.min(page * PAGE_SIZE, total)
	return (
		<nav
			aria-label="Index pages"
			className="border-rule mt-12 flex flex-wrap items-center justify-between gap-4 border-t pt-4"
		>
			<Data className="text-ground-muted tabular-nums">
				{from.toLocaleString('en-US')}–{to.toLocaleString('en-US')} of{' '}
				{total.toLocaleString('en-US')}
			</Data>
			<div className="flex items-center gap-4">
				{page > 1 ? (
					<Link
						to={hrefWith({ page: page - 1 })}
						rel="prev"
						className="font-data text-data-sm text-link tracking-[0.12em] uppercase underline underline-offset-4"
					>
						← Previous
					</Link>
				) : (
					<span className="font-data text-data-sm text-ground-muted tracking-[0.12em] uppercase opacity-40">
						← Previous
					</span>
				)}
				<Data className="tabular-nums">
					{page} / {pageCount}
				</Data>
				{page < pageCount ? (
					<Link
						to={hrefWith({ page: page + 1 })}
						rel="next"
						className="font-data text-data-sm text-link tracking-[0.12em] uppercase underline underline-offset-4"
					>
						Next →
					</Link>
				) : (
					<span className="font-data text-data-sm text-ground-muted tracking-[0.12em] uppercase opacity-40">
						Next →
					</span>
				)}
			</div>
		</nav>
	)
}
